### ISSUE TITLE
data type discrepancy btw R and gama

### ISSUE THREAD

**Issue by meta00** [r-and-gama/rama#76]
In save_to_rama, types of parameters are checked whether they are integer, float or string

` 
m_type <- "STRING"
    if (is.numeric(val)) {
        if (is.integer(val)) {
          m_type <- "INT"
        } else m_type <- "FLOAT"
      }

`
However, in R a number is default to be "double/float". For example "1" is considered "double/float" in R. Should it be "int" in gama?

How about "NA" and "null" and "factor", they are all "STRING" in gama?

**Comment by choisy** [comment]
Good questions...
For the first question, I suggest that:

- when a `gaml` file is read, the `experiment` that is created uses the same types as in the `gaml` file: if it's integer in the `gaml` file, we put integer in the `experiment` object, if it's double in the `gaml` file, we put `numeric` in the experiment.
- when an `experiment` is saved to a `gaml` file, we do the same. So, if the types are not actively changed on the `experiment` object, the types should be the same in the original `gaml` file and the one that is generated from the `experiment` object.

As for the second question, mmmm.... I don't know. I haven't thought of this. Would you have a concrete example where NA, NULL and factor are present in an experiment so that I can think of it?

**Comment by meta00** [comment]
First question:

A value in gaml is 'int', when it is read into rama, it is cast into 'numeric'.
This value numeric, when transfer from rama to gama, it is cast into 'float'.

We need a better type transformation, not only using is.numeric/is.integer etc. of R, like detect floating point?

Second question: @benoitgaudou if we pass "NA" or "NULL" to gama, what will happen?

**Comment by choisy** [comment]
Then, what we should do when ready `gaml` files is making sure that INT in `gaml` become `integer` class in R. And vice versa. That should solve the first question right?

Second question: I still don't quite see where these `NA` or `NULL` values could come from. Do you have any example?

**Comment by meta00** [comment]
For 1st question, to add:
- Get types of parameters from `gaml`, probably by improving `show_experiment`
- Improve `check_experiment` to check types.

For 2nd question, `is.experiment` already check for `NA`. Can add `NULL` if it creates errors in gama.

**Comment by choisy** [comment]
This issue is linked to issue #87
